name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        BUILD_TYPE: ["Debug"]
        os: [ windows-2022 ]
    steps:
    - uses: actions/checkout@v2

    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Install coverage unmangle tool
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: rustfilt

    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      continue-on-error: true  # WARNING: only for this example, remove it!
      with:
        command: clippy
        args: -- -D warnings

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

    # coverage
    - name: run cmake
      run: > 
        cmake . -DCMAKE_BUILD_TYPE=Debug -B build
    
    - name: run coverage
      run: |
        cmake --build build --config Debug --target cov_all

    - name: Upload Report to Codecov
      if: ${{ matrix.BUILD_TYPE == 'Debug' }}
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.json
        fail_ci_if_error: true
        functionalities: fix